# Generated by Django 6.0.1 on 2026-01-12 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_license",
                        message="Numer musi składać się z 3 dużych liter i 5 cyfr.",
                        regex="^[A-Z]{3}\\d{5}$",
                    )
                ],
            ),
        ),
    ]
